### ISSUE TITLE
[Linux] Minor launch script issue

### ISSUE THREAD

**Issue by Adam-Stambaugh** [nxengine/nxengine-evo#117]
This is a minor concern, but not all distributions use the same version of Sh (some even just have a link to Bash instead of Sh). The Linux startup script (named nx by default) in the release builds uses Sh.

Sh (on most distributions that actually have Sh) don't support "==" for the if-then statement. A couple of solutions is to replace "#!/bin/sh" with "#!/bin/bash" or replace "==" with "=".

Thank you for your time.

**Comment by nlburgin** [comment]
I think you're mistaken. There's no Bashisms in here.

```sh
#!/bin/sh

ARCH=`uname -m`

# Set the libpath and pick the proper binary
if [ "$ARCH" == "x86_64" ]; then
        export LD_LIBRARY_PATH="./lib64:${LD_LIBRARY_PATH}"
        ./nx.x86_64.bin "$@"
else
        export LD_LIBRARY_PATH="./lib:${LD_LIBRARY_PATH}"
        ./nx.x86_32.bin "$@"
fi
```

Unlike Bash, minimal/standard Bourne shells don't support `$(( $VAR == VALUE )) syntax.

However, the [ "$VAR" == "STRING" ] construct doesn't rely on shell syntax at all, it invokes an executable whose name is actually '`[`' .

This is a variant of the `test` command, part of GNU coreutils and also implemented by Busybox. If you run `ls /usr/bin` you'll almost certainly find it at the top of the list.

And also, I just tested the script on Ubuntu (which uses Dash instead of Bash for `/bin/sh`), and it ran fine without changing the shebang to point to Bash.

 There are no bashisms in this script, it is compliant POSIX Bourne Shell.

**Comment by Adam-Stambaugh** [comment]
I didn't know that about "[". That's neat.

Still, I imagine it's still going to have something to do with it as the version of Dash on Debian Stretch doesn't support it (unexpected operator). Switching it to Bash or using "=" instead of "==" fixed it for me. I know a while back people were wanting to make it a bit more familiar with people that work in C.

**Comment by nlburgin** [comment]
>the version of Dash on Debian Stretch doesn't support it (unexpected operator).

Interesting. Did it say what was the unexpected operator? Maybe the ${VAR} syntax later in the script was throwing it off.

**Comment by Adam-Stambaugh** [comment]
Here's the entire error.

``6: [: x86_64: unexpected operator

Though, given what you told me, I wonder if Dash or Bash has "[" compiled in for whatever reason.

**Comment by nlburgin** [comment]
It shouldn't be compiled in, it should be in `/usr/bin`

**Comment by Adam-Stambaugh** [comment]
It probably just has an older version. "==" didn't always work, that's a bit of a newer (newer as in the last ten years) thing people brought in from C, I'm fairly sure. Debian Stretch probably just has an older implementation of Dash with "[" compiled in. Either way, "=" is compatible with those older versions.

**Comment by nlburgin** [comment]
Wait a minute. I was running the script from a file manager and assumed the fact that it ran meant no error.

But I just ran it in a shell, and even though it worked, it printed the error message you listed right before successfully launching the game anyway and printing out a bunch of game output

**Comment by Adam-Stambaugh** [comment]
Oh yeah. It defaults to running the 32-bit version if it hits that error.

**Comment by nlburgin** [comment]
Oh, weird. I thought it was running correctly, but actually not.

**Comment by nlburgin** [comment]
I think the problem must specifically be with Dash's built-in `[` implementation. Running it with bash fixes it, and the following change also fixes it:

```sh
#!/bin/sh

ARCH=`uname -m`

# Set the libpath and pick the proper binary
if /usr/bin/[ "$ARCH" == "x86_64" ]; then
        export LD_LIBRARY_PATH="./lib64:${LD_LIBRARY_PATH}"
        ./nx.x86_64.bin "$@"
else
        export LD_LIBRARY_PATH="./lib:${LD_LIBRARY_PATH}"
        ./nx.x86_32.bin "$@"
fi
```

It can apparently still run in Dash as long as it's specifically invoking the `[` in `/usr/bin/` rather than the one built in to Dash.

**Comment by isage** [comment]
`==` is a bashism, you are right. Only `=` is defined by POSIX.

**Comment by Adam-Stambaugh** [comment]
I was wrong (mostly) about the cause, but it got fixed regardless. I should look more into how bash work. I've been using it for years and just didn't think too much about it.

Either way, thank you for your time!

**Comment by nlburgin** [comment]
Looking for a third implementation, I tried #!/bin/sh

ARCH=`uname -m`

```sh
# Set the libpath and pick the proper binary
if /usr/bin/busybox [ "$ARCH" == "x86_64" ]; then
        export LD_LIBRARY_PATH="./lib64:${LD_LIBRARY_PATH}"
        ./nx.x86_64.bin "$@"
else
        export LD_LIBRARY_PATH="./lib:${LD_LIBRARY_PATH}"
        ./nx.x86_32.bin "$@"
fi
```

So it looks like the `==` syntax is indeed exclusive to GNU versions of `[`, whether `[` is built-in to the shell or invoked from its own executable.

**Comment by isage** [comment]
Fixed.

**Comment by nlburgin** [comment]
@Adam-Stambaugh  Actually you were mostly right. It seems like only versions of `[` that support `==` syntax are the one built-in to Bash, and the standalone one provided by GNU Coreutils. 

The latter can invoked by other shells by explicitly running the full path `/usr/bin/[` (assuming it's a GNU/Linux system and not something else like BSD or Busybox/Linux), but either way it's still not standard.

Though what makes me curious now, is why there's a separate `[` executable to begin with if it's also built into the shell? Weird.

**Comment by Adam-Stambaugh** [comment]
@nlburgin I remember these issues coming up before, especially when Ubuntu first came around and more people started coming over. Granted, I don't have the greatest understanding about the underlying technologies and it's been a while since I've participated in that discussion.

Dash was designed to be more lightweight. It probably had most operators compiled in to ensure it would only use its own lightweight ones. However, anymore most arguments in favor of Dash aren't exactly relevant anymore (even RPis don't really benefit from how "lightweight" Dash is). I didn't even realize Debian still had it included until I saw that error pop up. Most Distros I see anymore just have sh point to bash.

**Comment by nlburgin** [comment]
@Adam-Stambaugh 

In a workload that has a ton of shell scripts running at once, it's possible that Dash's lower memory footprint may still have some relevance. But most of the time, yeah, it's not that noticeable.

I think the idea in Debian was to speed up the boot process, but that may no longer be relevant since they replaced the old init system with Systemd, and I don't think systemd uses as many shell scripts.
