### ISSUE TITLE
Chako doesn't sleep.

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#38]
While obtaining Chako's lipstick, I encountered some kind of bug where Chako's sound didn't play and Chako's animation or object didn't change. The only interesting line in the console is "`error << FindObjectByID2: ID2 0300 found: type OBJ_CHACO(93); coords: (206, 96) >>`" while running script 211.

Here's a screenshot of the final room state.
![screenshot from 2018-07-03 15-42-58](https://user-images.githubusercontent.com/8621403/42243823-33075534-7ed8-11e8-895e-369d066f0f49.png)

When spoken to, Chako uses her usual 'awake' dialogue.

Steps to reproduce (if you're unsure):
1) Enter Chako's house for the _first time_ in a playthrough.
(It should be okay to use a savegame that has started from here.)
2) Speak to Chako.
3) Check the fireplace.
4) Use the bed.

**Comment by isage** [comment]
Do you have a savefile before that?

**Comment by Yukitty** [comment]
Unfortunately not. 😥 I foolishly did an impulse save the moment I realized Chako's lipstick did actually make it into my inventory. (I'm currently rushing through the game just to find all the rooms that need out-of-bounds tiles, and it just happens to be a good playtesting session for weird bugs like this along the way.)

**Comment by Yukitty** [comment]
Got it.
[profile-chako.zip](https://github.com/nxengine/nxengine-evo/files/2161300/profile-chako.zip)

**Comment by isage** [comment]
Ugh. First, we're missing AI for chaco, so there's no sleeping state for her. That's easily fixable (i've actually done that already).
But, we don't have a sprite frame for her either. And that's bad, because sifedit is a piece of crap, honestly.

**Comment by isage** [comment]
Should be fixed now.

**Comment by Yukitty** [comment]
![screenshot from 2018-07-03 18-52-46](https://user-images.githubusercontent.com/8621403/42249697-5614c010-7ef2-11e8-8798-012e847931d0.png)
😱

**Comment by isage** [comment]
You probably forgot to copy over new sprites.sif

**Comment by Yukitty** [comment]
Ah. After some fiddling, I managed to get sifedit to compile... and it barely runs and won't let me save, so I can't fix anything sprite-related just yet.

It looks like when you added Sue to the flying dragon's maw for the ending sequence, you used the wrong version of sprites.sif so Chaco's sprite is missing again. Therefore... You forgot to copy over the new sprites.sif yourself?
